version: '3.8'
services:

  backend:
    container_name: backend
    build:
      context: ./backend
    image: backend:1.0.0
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - env=dev
      - database=sqlite:///database.sqlite3
    # env_file:
    #   - ./backend/.env
    networks:
      - main

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: frontend:1.0.0
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - env=dev
      - NEXT_PUBLIC_GRAPHQL_SERVER_URL=http://localhost:8000/graphql
    # env_file:
    #   - ./frontend/.env
    networks:
      - main

networks:
  main:
